#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEALTHHANDBOOK.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYNHATHUOC")]
	public partial class QUANLYTIENTHUOCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTHUOC(THUOC instance);
    partial void UpdateTHUOC(THUOC instance);
    partial void DeleteTHUOC(THUOC instance);
    #endregion
		
		public QUANLYTIENTHUOCDataContext() : 
				base(global::HEALTHHANDBOOK.Properties.Settings.Default.QUANLYNHATHUOCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYTIENTHUOCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYTIENTHUOCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYTIENTHUOCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYTIENTHUOCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<THUOC> THUOCs
		{
			get
			{
				return this.GetTable<THUOC>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUOC")]
	public partial class THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_THUOC;
		
		private string _TENTHUOC;
		
		private string _TENGOIKHAC;
		
		private string _MOTA;
		
		private System.Nullable<double> _GIAGOC;
		
		private string _CONGDUNG;
		
		private System.Nullable<double> _GIABAN;
		
		private string _THANHPHAN;
		
		private string _CHIDINH;
		
		private string _CHONGCHIDINH;
		
		private string _HSD;
		
		private string _NHASANXUAT;
		
		private string _LUY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_THUOCChanging(int value);
    partial void OnID_THUOCChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    partial void OnTENGOIKHACChanging(string value);
    partial void OnTENGOIKHACChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnGIAGOCChanging(System.Nullable<double> value);
    partial void OnGIAGOCChanged();
    partial void OnCONGDUNGChanging(string value);
    partial void OnCONGDUNGChanged();
    partial void OnGIABANChanging(System.Nullable<double> value);
    partial void OnGIABANChanged();
    partial void OnTHANHPHANChanging(string value);
    partial void OnTHANHPHANChanged();
    partial void OnCHIDINHChanging(string value);
    partial void OnCHIDINHChanged();
    partial void OnCHONGCHIDINHChanging(string value);
    partial void OnCHONGCHIDINHChanged();
    partial void OnHSDChanging(string value);
    partial void OnHSDChanged();
    partial void OnNHASANXUATChanging(string value);
    partial void OnNHASANXUATChanged();
    partial void OnLUYChanging(string value);
    partial void OnLUYChanged();
    #endregion
		
		public THUOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THUOC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_THUOC
		{
			get
			{
				return this._ID_THUOC;
			}
			set
			{
				if ((this._ID_THUOC != value))
				{
					this.OnID_THUOCChanging(value);
					this.SendPropertyChanging();
					this._ID_THUOC = value;
					this.SendPropertyChanged("ID_THUOC");
					this.OnID_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGOIKHAC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENGOIKHAC
		{
			get
			{
				return this._TENGOIKHAC;
			}
			set
			{
				if ((this._TENGOIKHAC != value))
				{
					this.OnTENGOIKHACChanging(value);
					this.SendPropertyChanging();
					this._TENGOIKHAC = value;
					this.SendPropertyChanged("TENGOIKHAC");
					this.OnTENGOIKHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAGOC", DbType="Float")]
		public System.Nullable<double> GIAGOC
		{
			get
			{
				return this._GIAGOC;
			}
			set
			{
				if ((this._GIAGOC != value))
				{
					this.OnGIAGOCChanging(value);
					this.SendPropertyChanging();
					this._GIAGOC = value;
					this.SendPropertyChanged("GIAGOC");
					this.OnGIAGOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONGDUNG", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CONGDUNG
		{
			get
			{
				return this._CONGDUNG;
			}
			set
			{
				if ((this._CONGDUNG != value))
				{
					this.OnCONGDUNGChanging(value);
					this.SendPropertyChanging();
					this._CONGDUNG = value;
					this.SendPropertyChanged("CONGDUNG");
					this.OnCONGDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Float")]
		public System.Nullable<double> GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHPHAN", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string THANHPHAN
		{
			get
			{
				return this._THANHPHAN;
			}
			set
			{
				if ((this._THANHPHAN != value))
				{
					this.OnTHANHPHANChanging(value);
					this.SendPropertyChanging();
					this._THANHPHAN = value;
					this.SendPropertyChanged("THANHPHAN");
					this.OnTHANHPHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIDINH", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CHIDINH
		{
			get
			{
				return this._CHIDINH;
			}
			set
			{
				if ((this._CHIDINH != value))
				{
					this.OnCHIDINHChanging(value);
					this.SendPropertyChanging();
					this._CHIDINH = value;
					this.SendPropertyChanged("CHIDINH");
					this.OnCHIDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHONGCHIDINH", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CHONGCHIDINH
		{
			get
			{
				return this._CHONGCHIDINH;
			}
			set
			{
				if ((this._CHONGCHIDINH != value))
				{
					this.OnCHONGCHIDINHChanging(value);
					this.SendPropertyChanging();
					this._CHONGCHIDINH = value;
					this.SendPropertyChanged("CHONGCHIDINH");
					this.OnCHONGCHIDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSD", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string HSD
		{
			get
			{
				return this._HSD;
			}
			set
			{
				if ((this._HSD != value))
				{
					this.OnHSDChanging(value);
					this.SendPropertyChanging();
					this._HSD = value;
					this.SendPropertyChanged("HSD");
					this.OnHSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHASANXUAT", DbType="NVarChar(150)")]
		public string NHASANXUAT
		{
			get
			{
				return this._NHASANXUAT;
			}
			set
			{
				if ((this._NHASANXUAT != value))
				{
					this.OnNHASANXUATChanging(value);
					this.SendPropertyChanging();
					this._NHASANXUAT = value;
					this.SendPropertyChanged("NHASANXUAT");
					this.OnNHASANXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUY", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LUY
		{
			get
			{
				return this._LUY;
			}
			set
			{
				if ((this._LUY != value))
				{
					this.OnLUYChanging(value);
					this.SendPropertyChanging();
					this._LUY = value;
					this.SendPropertyChanged("LUY");
					this.OnLUYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
