#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYNHATHUOC.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANGLYNHATHUOC")]
	public partial class QUANLYNHATHUOCDATADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTHD(CTHD instance);
    partial void UpdateCTHD(CTHD instance);
    partial void DeleteCTHD(CTHD instance);
    partial void InsertTHUOC(THUOC instance);
    partial void UpdateTHUOC(THUOC instance);
    partial void DeleteTHUOC(THUOC instance);
    partial void InsertDONVITINH(DONVITINH instance);
    partial void UpdateDONVITINH(DONVITINH instance);
    partial void DeleteDONVITINH(DONVITINH instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertLOAITHUOC(LOAITHUOC instance);
    partial void UpdateLOAITHUOC(LOAITHUOC instance);
    partial void DeleteLOAITHUOC(LOAITHUOC instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertNHAPHANG(NHAPHANG instance);
    partial void UpdateNHAPHANG(NHAPHANG instance);
    partial void DeleteNHAPHANG(NHAPHANG instance);
    partial void InsertQUYDINH(QUYDINH instance);
    partial void UpdateQUYDINH(QUYDINH instance);
    partial void DeleteQUYDINH(QUYDINH instance);
    #endregion
		
		public QUANLYNHATHUOCDATADataContext() : 
				base(global::QUANLYNHATHUOC.Properties.Settings.Default.QUANGLYNHATHUOCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYNHATHUOCDATADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYNHATHUOCDATADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYNHATHUOCDATADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYNHATHUOCDATADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTHD> CTHDs
		{
			get
			{
				return this.GetTable<CTHD>();
			}
		}
		
		public System.Data.Linq.Table<THUOC> THUOCs
		{
			get
			{
				return this.GetTable<THUOC>();
			}
		}
		
		public System.Data.Linq.Table<DONVITINH> DONVITINHs
		{
			get
			{
				return this.GetTable<DONVITINH>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<LOAITHUOC> LOAITHUOCs
		{
			get
			{
				return this.GetTable<LOAITHUOC>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<NHAPHANG> NHAPHANGs
		{
			get
			{
				return this.GetTable<NHAPHANG>();
			}
		}
		
		public System.Data.Linq.Table<QUYDINH> QUYDINHs
		{
			get
			{
				return this.GetTable<QUYDINH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHD")]
	public partial class CTHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCTHD;
		
		private string _TENTHUOC;
		
		private System.Nullable<int> _DVT;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _GIABAN;
		
		private string _THANHTIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCTHDChanging(int value);
    partial void OnIDCTHDChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    partial void OnDVTChanging(System.Nullable<int> value);
    partial void OnDVTChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnGIABANChanging(string value);
    partial void OnGIABANChanged();
    partial void OnTHANHTIENChanging(string value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public CTHD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCTHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCTHD
		{
			get
			{
				return this._IDCTHD;
			}
			set
			{
				if ((this._IDCTHD != value))
				{
					this.OnIDCTHDChanging(value);
					this.SendPropertyChanging();
					this._IDCTHD = value;
					this.SendPropertyChanged("IDCTHD");
					this.OnIDCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(100)")]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="Int")]
		public System.Nullable<int> DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="VarChar(50)")]
		public string GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="VarChar(50)")]
		public string THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUOC")]
	public partial class THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTHUOC;
		
		private string _TENTHUOC;
		
		private string _THANHPHAN;
		
		private string _CHIDINH;
		
		private string _LIEUDUNG;
		
		private string _CHONGCHIDINH;
		
		private string _THANTRONG;
		
		private string _PHANUNGPHU;
		
		private string _TUONGTACTHUOC;
		
		private string _TRINHBAYDONGGOI;
		
		private string _NHASANXUAT;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _DONVI;
		
		private string _GIABAN;
		
		private string _HINHANH;
		
		private string _LOAITHUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTHUOCChanging(int value);
    partial void OnIDTHUOCChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    partial void OnTHANHPHANChanging(string value);
    partial void OnTHANHPHANChanged();
    partial void OnCHIDINHChanging(string value);
    partial void OnCHIDINHChanged();
    partial void OnLIEUDUNGChanging(string value);
    partial void OnLIEUDUNGChanged();
    partial void OnCHONGCHIDINHChanging(string value);
    partial void OnCHONGCHIDINHChanged();
    partial void OnTHANTRONGChanging(string value);
    partial void OnTHANTRONGChanged();
    partial void OnPHANUNGPHUChanging(string value);
    partial void OnPHANUNGPHUChanged();
    partial void OnTUONGTACTHUOCChanging(string value);
    partial void OnTUONGTACTHUOCChanged();
    partial void OnTRINHBAYDONGGOIChanging(string value);
    partial void OnTRINHBAYDONGGOIChanged();
    partial void OnNHASANXUATChanging(string value);
    partial void OnNHASANXUATChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDONVIChanging(string value);
    partial void OnDONVIChanged();
    partial void OnGIABANChanging(string value);
    partial void OnGIABANChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnLOAITHUOCChanging(string value);
    partial void OnLOAITHUOCChanged();
    #endregion
		
		public THUOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTHUOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTHUOC
		{
			get
			{
				return this._IDTHUOC;
			}
			set
			{
				if ((this._IDTHUOC != value))
				{
					this.OnIDTHUOCChanging(value);
					this.SendPropertyChanging();
					this._IDTHUOC = value;
					this.SendPropertyChanged("IDTHUOC");
					this.OnIDTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(100)")]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHPHAN", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string THANHPHAN
		{
			get
			{
				return this._THANHPHAN;
			}
			set
			{
				if ((this._THANHPHAN != value))
				{
					this.OnTHANHPHANChanging(value);
					this.SendPropertyChanging();
					this._THANHPHAN = value;
					this.SendPropertyChanged("THANHPHAN");
					this.OnTHANHPHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIDINH", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CHIDINH
		{
			get
			{
				return this._CHIDINH;
			}
			set
			{
				if ((this._CHIDINH != value))
				{
					this.OnCHIDINHChanging(value);
					this.SendPropertyChanging();
					this._CHIDINH = value;
					this.SendPropertyChanged("CHIDINH");
					this.OnCHIDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEUDUNG", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LIEUDUNG
		{
			get
			{
				return this._LIEUDUNG;
			}
			set
			{
				if ((this._LIEUDUNG != value))
				{
					this.OnLIEUDUNGChanging(value);
					this.SendPropertyChanging();
					this._LIEUDUNG = value;
					this.SendPropertyChanged("LIEUDUNG");
					this.OnLIEUDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHONGCHIDINH", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CHONGCHIDINH
		{
			get
			{
				return this._CHONGCHIDINH;
			}
			set
			{
				if ((this._CHONGCHIDINH != value))
				{
					this.OnCHONGCHIDINHChanging(value);
					this.SendPropertyChanging();
					this._CHONGCHIDINH = value;
					this.SendPropertyChanged("CHONGCHIDINH");
					this.OnCHONGCHIDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANTRONG", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string THANTRONG
		{
			get
			{
				return this._THANTRONG;
			}
			set
			{
				if ((this._THANTRONG != value))
				{
					this.OnTHANTRONGChanging(value);
					this.SendPropertyChanging();
					this._THANTRONG = value;
					this.SendPropertyChanged("THANTRONG");
					this.OnTHANTRONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHANUNGPHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string PHANUNGPHU
		{
			get
			{
				return this._PHANUNGPHU;
			}
			set
			{
				if ((this._PHANUNGPHU != value))
				{
					this.OnPHANUNGPHUChanging(value);
					this.SendPropertyChanging();
					this._PHANUNGPHU = value;
					this.SendPropertyChanged("PHANUNGPHU");
					this.OnPHANUNGPHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUONGTACTHUOC", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TUONGTACTHUOC
		{
			get
			{
				return this._TUONGTACTHUOC;
			}
			set
			{
				if ((this._TUONGTACTHUOC != value))
				{
					this.OnTUONGTACTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TUONGTACTHUOC = value;
					this.SendPropertyChanged("TUONGTACTHUOC");
					this.OnTUONGTACTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHBAYDONGGOI", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TRINHBAYDONGGOI
		{
			get
			{
				return this._TRINHBAYDONGGOI;
			}
			set
			{
				if ((this._TRINHBAYDONGGOI != value))
				{
					this.OnTRINHBAYDONGGOIChanging(value);
					this.SendPropertyChanging();
					this._TRINHBAYDONGGOI = value;
					this.SendPropertyChanged("TRINHBAYDONGGOI");
					this.OnTRINHBAYDONGGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHASANXUAT", DbType="NChar(10)")]
		public string NHASANXUAT
		{
			get
			{
				return this._NHASANXUAT;
			}
			set
			{
				if ((this._NHASANXUAT != value))
				{
					this.OnNHASANXUATChanging(value);
					this.SendPropertyChanging();
					this._NHASANXUAT = value;
					this.SendPropertyChanged("NHASANXUAT");
					this.OnNHASANXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI", DbType="NVarChar(50)")]
		public string DONVI
		{
			get
			{
				return this._DONVI;
			}
			set
			{
				if ((this._DONVI != value))
				{
					this.OnDONVIChanging(value);
					this.SendPropertyChanging();
					this._DONVI = value;
					this.SendPropertyChanged("DONVI");
					this.OnDONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="NVarChar(50)")]
		public string GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(50)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAITHUOC", DbType="NVarChar(50)")]
		public string LOAITHUOC
		{
			get
			{
				return this._LOAITHUOC;
			}
			set
			{
				if ((this._LOAITHUOC != value))
				{
					this.OnLOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._LOAITHUOC = value;
					this.SendPropertyChanged("LOAITHUOC");
					this.OnLOAITHUOCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVITINH")]
	public partial class DONVITINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDVT;
		
		private string _TEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDVTChanging(int value);
    partial void OnIDDVTChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    #endregion
		
		public DONVITINH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDVT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDVT
		{
			get
			{
				return this._IDDVT;
			}
			set
			{
				if ((this._IDDVT != value))
				{
					this.OnIDDVTChanging(value);
					this.SendPropertyChanging();
					this._IDDVT = value;
					this.SendPropertyChanged("IDDVT");
					this.OnIDDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(50)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHOADON;
		
		private System.Nullable<System.DateTime> _NGAYTAOHD;
		
		private System.Nullable<int> _NGUOITAOHD;
		
		private string _TONGTIEN;
		
		private System.Nullable<int> _IDCTHD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHOADONChanging(int value);
    partial void OnIDHOADONChanged();
    partial void OnNGAYTAOHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOHDChanged();
    partial void OnNGUOITAOHDChanging(System.Nullable<int> value);
    partial void OnNGUOITAOHDChanged();
    partial void OnTONGTIENChanging(string value);
    partial void OnTONGTIENChanged();
    partial void OnIDCTHDChanging(System.Nullable<int> value);
    partial void OnIDCTHDChanged();
    #endregion
		
		public HOADON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHOADON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHOADON
		{
			get
			{
				return this._IDHOADON;
			}
			set
			{
				if ((this._IDHOADON != value))
				{
					this.OnIDHOADONChanging(value);
					this.SendPropertyChanging();
					this._IDHOADON = value;
					this.SendPropertyChanged("IDHOADON");
					this.OnIDHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAOHD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAOHD
		{
			get
			{
				return this._NGAYTAOHD;
			}
			set
			{
				if ((this._NGAYTAOHD != value))
				{
					this.OnNGAYTAOHDChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAOHD = value;
					this.SendPropertyChanged("NGAYTAOHD");
					this.OnNGAYTAOHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITAOHD", DbType="Int")]
		public System.Nullable<int> NGUOITAOHD
		{
			get
			{
				return this._NGUOITAOHD;
			}
			set
			{
				if ((this._NGUOITAOHD != value))
				{
					this.OnNGUOITAOHDChanging(value);
					this.SendPropertyChanging();
					this._NGUOITAOHD = value;
					this.SendPropertyChanged("NGUOITAOHD");
					this.OnNGUOITAOHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="VarChar(50)")]
		public string TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCTHD", DbType="Int")]
		public System.Nullable<int> IDCTHD
		{
			get
			{
				return this._IDCTHD;
			}
			set
			{
				if ((this._IDCTHD != value))
				{
					this.OnIDCTHDChanging(value);
					this.SendPropertyChanging();
					this._IDCTHD = value;
					this.SendPropertyChanged("IDCTHD");
					this.OnIDCTHDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITHUOC")]
	public partial class LOAITHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDLOAITHUOC;
		
		private string _TENLOAITHUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLOAITHUOCChanging(int value);
    partial void OnIDLOAITHUOCChanged();
    partial void OnTENLOAITHUOCChanging(string value);
    partial void OnTENLOAITHUOCChanged();
    #endregion
		
		public LOAITHUOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLOAITHUOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDLOAITHUOC
		{
			get
			{
				return this._IDLOAITHUOC;
			}
			set
			{
				if ((this._IDLOAITHUOC != value))
				{
					this.OnIDLOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._IDLOAITHUOC = value;
					this.SendPropertyChanged("IDLOAITHUOC");
					this.OnIDLOAITHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAITHUOC", DbType="NVarChar(100)")]
		public string TENLOAITHUOC
		{
			get
			{
				return this._TENLOAITHUOC;
			}
			set
			{
				if ((this._TENLOAITHUOC != value))
				{
					this.OnTENLOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENLOAITHUOC = value;
					this.SendPropertyChanged("TENLOAITHUOC");
					this.OnTENLOAITHUOCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNGUOIDUNG;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _QUEQUAN;
		
		private System.Nullable<int> _CMND;
		
		private string _HINHANH;
		
		private System.Nullable<int> _TRINHDO;
		
		private System.Nullable<int> _QUYEN;
		
		private System.Nullable<int> _SDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNGUOIDUNGChanging(int value);
    partial void OnIDNGUOIDUNGChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnQUEQUANChanging(string value);
    partial void OnQUEQUANChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnTRINHDOChanging(System.Nullable<int> value);
    partial void OnTRINHDOChanged();
    partial void OnQUYENChanging(System.Nullable<int> value);
    partial void OnQUYENChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNGUOIDUNG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNGUOIDUNG
		{
			get
			{
				return this._IDNGUOIDUNG;
			}
			set
			{
				if ((this._IDNGUOIDUNG != value))
				{
					this.OnIDNGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._IDNGUOIDUNG = value;
					this.SendPropertyChanged("IDNGUOIDUNG");
					this.OnIDNGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUEQUAN", DbType="NVarChar(100)")]
		public string QUEQUAN
		{
			get
			{
				return this._QUEQUAN;
			}
			set
			{
				if ((this._QUEQUAN != value))
				{
					this.OnQUEQUANChanging(value);
					this.SendPropertyChanging();
					this._QUEQUAN = value;
					this.SendPropertyChanged("QUEQUAN");
					this.OnQUEQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(50)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO", DbType="Int")]
		public System.Nullable<int> TRINHDO
		{
			get
			{
				return this._TRINHDO;
			}
			set
			{
				if ((this._TRINHDO != value))
				{
					this.OnTRINHDOChanging(value);
					this.SendPropertyChanging();
					this._TRINHDO = value;
					this.SendPropertyChanged("TRINHDO");
					this.OnTRINHDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="Int")]
		public System.Nullable<int> QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAPHANG")]
	public partial class NHAPHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNHAPHANG;
		
		private System.Nullable<System.DateTime> _NGAYNHAPHANG;
		
		private string _TENTHUOC;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _DVT;
		
		private string _GIANHAP;
		
		private string _THANHTIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNHAPHANGChanging(int value);
    partial void OnIDNHAPHANGChanged();
    partial void OnNGAYNHAPHANGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPHANGChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnGIANHAPChanging(string value);
    partial void OnGIANHAPChanged();
    partial void OnTHANHTIENChanging(string value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public NHAPHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNHAPHANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNHAPHANG
		{
			get
			{
				return this._IDNHAPHANG;
			}
			set
			{
				if ((this._IDNHAPHANG != value))
				{
					this.OnIDNHAPHANGChanging(value);
					this.SendPropertyChanging();
					this._IDNHAPHANG = value;
					this.SendPropertyChanged("IDNHAPHANG");
					this.OnIDNHAPHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAPHANG", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYNHAPHANG
		{
			get
			{
				return this._NGAYNHAPHANG;
			}
			set
			{
				if ((this._NGAYNHAPHANG != value))
				{
					this.OnNGAYNHAPHANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAPHANG = value;
					this.SendPropertyChanged("NGAYNHAPHANG");
					this.OnNGAYNHAPHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(50)")]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(50)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIANHAP", DbType="VarChar(50)")]
		public string GIANHAP
		{
			get
			{
				return this._GIANHAP;
			}
			set
			{
				if ((this._GIANHAP != value))
				{
					this.OnGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._GIANHAP = value;
					this.SendPropertyChanged("GIANHAP");
					this.OnGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="VarChar(50)")]
		public string THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYDINH")]
	public partial class QUYDINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDQUYDINH;
		
		private System.Nullable<int> _PHANTRAMCHIETKHAU;
		
		private string _TENQUYDINH;
		
		private string _TENTHUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDQUYDINHChanging(int value);
    partial void OnIDQUYDINHChanged();
    partial void OnPHANTRAMCHIETKHAUChanging(System.Nullable<int> value);
    partial void OnPHANTRAMCHIETKHAUChanged();
    partial void OnTENQUYDINHChanging(string value);
    partial void OnTENQUYDINHChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    #endregion
		
		public QUYDINH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQUYDINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDQUYDINH
		{
			get
			{
				return this._IDQUYDINH;
			}
			set
			{
				if ((this._IDQUYDINH != value))
				{
					this.OnIDQUYDINHChanging(value);
					this.SendPropertyChanging();
					this._IDQUYDINH = value;
					this.SendPropertyChanged("IDQUYDINH");
					this.OnIDQUYDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHANTRAMCHIETKHAU", DbType="Int")]
		public System.Nullable<int> PHANTRAMCHIETKHAU
		{
			get
			{
				return this._PHANTRAMCHIETKHAU;
			}
			set
			{
				if ((this._PHANTRAMCHIETKHAU != value))
				{
					this.OnPHANTRAMCHIETKHAUChanging(value);
					this.SendPropertyChanging();
					this._PHANTRAMCHIETKHAU = value;
					this.SendPropertyChanged("PHANTRAMCHIETKHAU");
					this.OnPHANTRAMCHIETKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENQUYDINH", DbType="NVarChar(50)")]
		public string TENQUYDINH
		{
			get
			{
				return this._TENQUYDINH;
			}
			set
			{
				if ((this._TENQUYDINH != value))
				{
					this.OnTENQUYDINHChanging(value);
					this.SendPropertyChanging();
					this._TENQUYDINH = value;
					this.SendPropertyChanged("TENQUYDINH");
					this.OnTENQUYDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(100)")]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
