<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYNHATHUOC" Class="QUANLYTIENTHUOCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CAOTHUONG\CAOTHUONG;Initial Catalog=QUANLYNHATHUOC;Integrated Security=True" SettingsObjectName="QUANLYNHATHUOC.Properties.Settings" SettingsPropertyName="QUANLYNHATHUOCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.THUOC" Member="THUOCs">
    <Type Name="THUOC">
      <Column Name="ID_THUOC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTHUOC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TENGOIKHAC" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GIAGOC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CONGDUNG" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GIABAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THANHPHAN" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CHIDINH" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CHONGCHIDINH" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HSD" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NHASANXUAT" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LUY" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>